use_frameworks!

platform :ios, '10.0'

target 'ZJModalTransition_Example' do
  pod 'ZJModalTransition', :path => '../'

  target 'ZJModalTransition_Tests' do
    inherit! :search_paths

    
  end
end
